spring:
  application:
    name: thesis_formatter
  datasource:
    url: "jdbc:mysql://localhost:3306/Formatter"
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 115MB
server:
  port: 8080
